steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/audio-to-text-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/audio-to-text-backend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/audio-to-text-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/audio-to-text-backend:latest'

  # Deploy API service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_WORKER}" = "true" ]; then
          # 队列模式：API 服务配置
          gcloud run deploy audio-to-text-backend \
            --image gcr.io/$PROJECT_ID/audio-to-text-backend:$COMMIT_SHA \
            --region ${_REGION} \
            --platform managed \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10 \
            --concurrency 80 \
            --timeout 300s \
            --set-env-vars "NODE_ENV=production,REDIS_ENABLED=true,REDIS_URL=${_REDIS_URL}"
        else
          # 同步模式：API 服务配置（更大内存处理转录）
          gcloud run deploy audio-to-text-backend \
            --image gcr.io/$PROJECT_ID/audio-to-text-backend:$COMMIT_SHA \
            --region ${_REGION} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10 \
            --concurrency 80 \
            --timeout 300s \
            --set-env-vars "NODE_ENV=production,REDIS_ENABLED=false"
        fi

  # Deploy Worker service (only if _DEPLOY_WORKER=true)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_WORKER}" = "true" ]; then
          echo "Deploying Worker service..."
          gcloud run deploy audio-to-text-worker \
            --image gcr.io/$PROJECT_ID/audio-to-text-backend:$COMMIT_SHA \
            --region ${_REGION} \
            --platform managed \
            --no-allow-unauthenticated \
            --memory 1Gi \
            --cpu 2 \
            --min-instances 1 \
            --max-instances 5 \
            --timeout 3600s \
            --command "node" \
            --args "dist/worker.js" \
            --set-env-vars "NODE_ENV=production,REDIS_ENABLED=true,REDIS_URL=${_REDIS_URL}"
        else
          echo "Skipping Worker deployment (DEPLOY_WORKER=${_DEPLOY_WORKER})"
        fi

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/audio-to-text-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/audio-to-text-backend:latest'

# Substitutions with defaults
substitutions:
  _REGION: 'us-west1'      # 美国西部
  _DEPLOY_WORKER: 'false'  # 默认不部署 Worker（同步模式）
  _REDIS_URL: ''           # 队列模式需要提供

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
